# Extra OpenBOR Wii dependencies on top of the official devkitPro image.
FROM devkitpro/devkitppc:latest

ENV WORKSPACE=/workspace

RUN git clone --depth 1 https://github.com/SumolX/libwupc.git /tmp/libwupc && \
    cp -a /tmp/libwupc/include/wupc /opt/devkitpro/portlibs/ppc/include/ && \
    cp -a /tmp/libwupc/lib/* /opt/devkitpro/portlibs/ppc/lib/ && \
    git clone --depth 1 https://github.com/SumolX/portlibs-ppc-libvpx.git /tmp/portlibs-ppc-libvpx && \
    cp -a /tmp/portlibs-ppc-libvpx/include/* /opt/devkitpro/portlibs/ppc/include/ && \
    cp -a /tmp/portlibs-ppc-libvpx/lib/* /opt/devkitpro/portlibs/ppc/lib/ && \
    rm -rf /tmp/libwupc /tmp/portlibs-ppc-libvpx

WORKDIR /workspace
