#!/usr/bin/env python3
"""Generate engine/wii/menufont.h and menufont_data.c for Wii menu GBK text."""

import os
from PIL import Image, ImageDraw, ImageFont

MENU_CHARS = "开始游戏音乐播放查看日志退出无模组文件夹中未找到共个当前总计"
WIDTH = 12
HEIGHT = 12
ROOT = os.path.join(os.path.dirname(__file__), "..", "engine", "wii")
OUT_H = os.path.join(ROOT, "menufont.h")
OUT_C = os.path.join(ROOT, "menufont_data.c")

FONT_CANDIDATES = [
    os.path.join(os.path.dirname(__file__), "fonts", "simhei.ttf"),
    r"C:\Windows\Fonts\simhei.ttf",
    r"C:\Windows\Fonts\msyh.ttc",
    r"C:\Windows\Fonts\simsun.ttc",
    r"C:\Windows\Fonts\simkai.ttf",
]


def find_font():
    for path in FONT_CANDIDATES:
        if os.path.isfile(path):
            return path
    raise SystemExit("No Chinese TTF font found. Install simhei.ttf or place it in tools/fonts/")


def collect_gb2312_chars():
    chars = set(MENU_CHARS)
    for lead in range(0xA1, 0xFF):
        for trail in range(0xA1, 0xFF):
            try:
                ch = bytes([lead, trail]).decode("gbk")
            except UnicodeDecodeError:
                continue
            if ch == "\ufffd":
                continue
            chars.add(ch)
    return chars


def glyph_to_rows(img):
    rows = []
    for y in range(HEIGHT):
        row = 0
        for x in range(WIDTH):
            if img.getpixel((x, y)) > 128:
                row |= 1 << (WIDTH - 1 - x)
        rows.append(row)
    return rows


def render_glyph(font, ch):
    img = Image.new("L", (WIDTH, HEIGHT), 0)
    draw = ImageDraw.Draw(img)
    bbox = draw.textbbox((0, 0), ch, font=font)
    tw = bbox[2] - bbox[0]
    th = bbox[3] - bbox[1]
    ox = (WIDTH - tw) // 2 - bbox[0]
    oy = (HEIGHT - th) // 2 - bbox[1]
    draw.text((ox, oy), ch, fill=255, font=font)
    return img


def main():
    font_path = find_font()
    font = ImageFont.truetype(font_path, 11)

    entries = []
    for ch in sorted(collect_gb2312_chars(), key=lambda c: c.encode("gbk")):
        gbk = ch.encode("gbk")
        if len(gbk) != 2:
            continue
        code = (gbk[0] << 8) | gbk[1]
        rows = glyph_to_rows(render_glyph(font, ch))
        entries.append((code, ch, rows))

    h_lines = [
        "/*",
        " * OpenBOR Wii menu font - auto-generated, do not edit by hand.",
        " * GBK 12x12 bitmap glyphs (GB2312 + menu strings).",
        " */",
        "#ifndef MENUFONT_H",
        "#define MENUFONT_H",
        "",
        "#define MENUFONT_WIDTH  12",
        "#define MENUFONT_HEIGHT 12",
        "",
        "typedef struct {",
        "\tunsigned short code;",
        "\tunsigned short data[12];",
        "} MenuFontGlyph;",
        "",
        "extern const MenuFontGlyph menu_font_glyphs[];",
        "#define MENUFONT_GLYPH_COUNT %d" % len(entries),
        "",
        "static inline const unsigned short *menu_font_lookup(unsigned char lead, unsigned char trail)",
        "{",
        "\tunsigned short code = ((unsigned short)lead << 8) | trail;",
        "\tint lo = 0;",
        "\tint hi = MENUFONT_GLYPH_COUNT - 1;",
        "",
        "\twhile(lo <= hi)",
        "\t{",
        "\t\tint mid = (lo + hi) >> 1;",
        "\t\tif(menu_font_glyphs[mid].code < code)",
        "\t\t{",
        "\t\t\tlo = mid + 1;",
        "\t\t}",
        "\t\telse if(menu_font_glyphs[mid].code > code)",
        "\t\t{",
        "\t\t\thi = mid - 1;",
        "\t\t}",
        "\t\telse",
        "\t\t{",
        "\t\t\treturn menu_font_glyphs[mid].data;",
        "\t\t}",
        "\t}",
        "\treturn 0;",
        "}",
        "",
        "#endif",
        "",
    ]

    c_lines = [
        "/* Auto-generated by tools/gen_menufont.py - do not edit by hand. */",
        '#include "menufont.h"',
        "",
        "const MenuFontGlyph menu_font_glyphs[] = {",
    ]

    for code, ch, rows in entries:
        hex_rows = ", ".join(f"0x{r:03X}" for r in rows)
        c_lines.append(f"\t{{ 0x{code:04X}, {{ {hex_rows} }} }}, /* {ch} */")

    c_lines += [
        "};",
        "",
    ]

    with open(OUT_H, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(h_lines))

    with open(OUT_C, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(c_lines))

    print(f"Wrote {len(entries)} glyphs to {OUT_H} and {OUT_C}")


if __name__ == "__main__":
    main()
